# 应用名称
spring.application.name: gccmap
# 应用服务 WEB 访问端口
server.port: 8080
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.gcc.gccmap.model
  configuration:
    map-underscore-to-camel-case: true
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/gccmap?useUnicode=true&characterEncoding=utf-8
    username: root
    password: gaojianjie
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    username: a13302361327@163.com
    password: ZCVICNOPANVYJSMG
    port: 465
    default-encoding: UTF-8
    protocol: smtps

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#swagger:
#  base-package: 'com.gcc.gccmap.controller'
#  base-path: '/**'
#  title: 'gccMap'
#  version: '1.0'
#  license-url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
#  license: 'The Apache License'
#  contact:
#    name: 'gjj'


